apiVersion: v1
kind: ConfigMap
metadata:
  name: vcverifier-testing-config
  namespace: ips-testing1
data:
  server.yaml: |-
    server:
      port: 3000
      staticDir: "views/static"
      templateDir: "views/"

    logging:
      level: "DEBUG"
      jsonLogging: "true"
      logRequests: "true"
      pathsToSkip: [/health]

    verifier:
      did: "did:web:vcverifier-testing.testing1.k8s-cluster.tango.rid-intrasoft.eu:did"
      tirAddress: "https://tir-ips.testing1.k8s-cluster.tango.rid-intrasoft.eu"
      sessionExpiry: 3600

    ssiKit:
      auditorURL: http://vcwaltid-ips-testing1:7003

    configRepo:
      configEndpoint: http://ips-dsc-credentials-config-service:8080/

