apiVersion: apps/v1
kind: Deployment
metadata:
  name: vcverifier
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vcverifier
  template:
    metadata:
      labels:
        app: vcverifier
    spec:
      containers:
      - name: verifier
        image: harbor.tango.rid-intrasoft.eu/ssikit-waltid/vcverifier:v1.0
        ports:
        - containerPort: 8080
