apiVersion: apps/v1
kind: Deployment
metadata:
  name: vcverifier
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vcverifier
  template:
    metadata:
      labels:
        app: vcverifier
    spec:
      containers:
      - name: verifier
        image: pablomarrtinez/verifier:v3.0.3
        ports:
        - containerPort: 8080
