apiVersion: apps/v1
kind: Deployment
metadata:
  name: vcverifier-testing
spec:
  selector:
    matchLabels:
      app: vcverifier-testing   
  template:
    metadata:
      labels:
        app: vcverifier-testing   
    spec:
      containers:
      - name: verifier
        image: pablomarrtinez/verifier:v3.0.4
        ports:
        - containerPort: 3000     
        env:
        - name: CONFIG_FILE
          value: /configs/server.yaml
        volumeMounts:
        - name: config-volume
          mountPath: /configs/
      volumes:
      - name: config-volume
        configMap:
          name: vcverifier-testing-config   
