apiVersion: apps/v1
kind: Deployment
metadata:
  name: vcverifier-testing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vcverifier-testing
  template:
    metadata:
      labels:
        app: vcverifier-testing
    spec:
      containers:
      - name: verifier
        image: pablomarrtinez/verifier:v3.0.4
        ports:
        - containerPort: 8080
