openapi: 3.0.3
info:
  title: DID Registry
  description: |
    The subset of the [DID Registry as defined by EBSI](https://api-pilot.ebsi.eu/docs/apis/did-registry/v4#/) as currently required by
    the [VCVerifier](https://github.com/FIWARE/VCVerifier).
  version: v4
tags:
  - name: DID
paths:
  /v4/identifiers/{did}:
    get:
      tags:
        - DID
      parameters:
        - $ref: '#/components/parameters/Did'
        - $ref: '#/components/parameters/ValidAt'
      operationId: getDIDDocument
      description: Gets the DID document corresponding to the DID.
      summary: Gets the DID document corresponding to the DID.
      responses:
        '200':
          description: Successfully returned the DID Document.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DIDDocument'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
components:
  parameters:
    Did:
      name: did
      description: Issuer's DID
      in: path
      required: true
      schema:
        type: string
        format: did
        example: did:ebsi:z6MksU6tMfbaDzvaRe5oFE4eZTVTV4HJM4fmQWWGsDGQVsEr
    ValidAt:
      name: valid-at
      description: This option is used to get a the version in the past of a DID document. It must be a date in ISO-8601 format
      in: query
      required: false
      schema:
        type: string
        format: date
        example: "2023-01-30"
  schemas:
    DIDDocument:
      type: object
      properties:
        id:
          type: string
          format: did
          example: did:ebsi:z6MksU6tMfbaDzvaRe5oFE4eZTVTV4HJM4fmQWWGsDGQVsEr
        '@context':
          description: Context used for describing the document
          type: array
          items:
            type: string
            example: "https://www.w3.org/ns/did/v1"
#       Standard defines list of strings but waltId provides object
#        assertionMethod:
#          description: "An assertionMethod property is used to specify a URL that contains information about a verificationMethod used for assertions."
#          type: array
#          items:
#            type: string
#        authentication:
#          description: "An authentication property is used to specify a URL that contains information about a verificationMethod used for authentication."
#          type: array
#          items:
#            type: string
        verificationMethod:
          description:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/JsonWebKey2020VerificationMethod'
              - $ref: '#/components/schemas/RsaVerificationKey2018VerificationMethod'
            discriminator:
              propertyName: type
              mapping:
                RsaVerificationKey2018: '#/components/schemas/RsaVerificationKey2018VerificationMethod'
                JsonWebKey2020: '#/components/schemas/JsonWebKey2020VerificationMethod'
      required:
        - id
        - '@context'
    VerificationMethod:
      type: object
      properties:
        id:
          type: string
          format: did
          example: did:ebsi:z6MksU6tMfbaDzvaRe5oFE4eZTVTV4HJM4fmQWWGsDGQVsEr
        type:
          type: string
          example: JsonWebKey2020
    RsaVerificationKey2018VerificationMethod:
      type: object
      allOf:
        - $ref: '#/components/schemas/VerificationMethod'
        - type: object
          properties:
            controller:
              type: string
            publicKeyJwk:
              $ref: '#/components/schemas/JWK'
    JsonWebKey2020VerificationMethod:
      type: object
      allOf:
        - $ref: '#/components/schemas/VerificationMethod'
        - type: object
          properties:
            controller:
              type: string
            publicKeyJwk:
              $ref: '#/components/schemas/JWK'
    JWK:
      type: object
      properties:
        alg:
          type: string
        kty:
          type: string
        kid:
          type: string
        n:
          type: string
        e:
          type: string
        x5u:
          type: string
        x5c:
          type: array
          items:
            type: string
        use:
          type: string
    ProblemDetails:
      type: object
      properties:
        type:
          description: An absolute URI that identifies the problem type. When dereferenced, it SHOULD provide human-readable documentation for the problem type.
          type: string
          format: uri
          ##default: about:blank
        title:
          description: A short summary of the problem type.
          type: string
          example: Internal Server Error
        status:
          description: The HTTP status code generated by the origin server for this occurrence of the problem.
          type: number
          example: 500
        detail:
          description: A human readable explanation specific to this occurrence of the problem.
          type: string
          example: Connection timeout
        instance:
          description: An absolute URI that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
          type: string
          format: uri