openapi: 3.0.3
info:
  title: Authorisation API 
  description: |
    The subset of the [Authentication API as defined by EBSI](https://api-pilot.ebsi.eu/docs/apis/authorisation/latest#/).
  version: v4
tags:
  - name: Auth
paths:
  /v4/token_m2m:
    post:
      tags:
        - Auth
      operationId: getTokenM2M
      description: Users receive access tokens after they present a valid EBSI Verifiable Credential and prove ownership over their DID.
      summary: Users receive access tokens after they present a valid EBSI Verifiable Credential and prove ownership over their DID.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/TokenRequestBody"
      responses:
        "200":
          description: Successfully returned the DID Document.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
components:
  schemas:
    TokenRequestBody:
      type: object
      properties:
        grant_type:
          type: string
          description: MUST be set to "vp_token"
          example: vp_token
        vp_token:
          description: Signed Verifiable Presentation. See also the VP Token schema definition.
          type: string
          example: eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6ImRpZDplYnNpOnp2SFdYMzU5QTNDdmZKbkNZYUFpQWRlI0YwcjVPeXRfbGFodnZ6Nk1XbFlzM21jWU5LWmlpUWRVZnF2OHRzaEhOOXcifQ.eyJpc3MiOiJkaWQ6ZWJzaTowMDAxMjM0NSIsImF1ZCI6ImRpZDplYnNpOnp4QTl0NFoydW9yRVZueDlualdVWXZSIiwibm9uY2UiOiIxMjM0NTY3ODkwIiwiZXhwIjoxNjY4NzU1NzY4LCJpYXQiOjE2Njg3NTQyNjgsInZwIjp7IkBjb250ZXh0IjpbImh0dHBzOi8vd3d3LnczLm9yZy8yMDE4L2NyZWRlbnRpYWxzL3YxIl0sInR5cGUiOlsiVmVyaWZpYWJsZVByZXNlbnRhdGlvbiJdLCJob2xkZXIiOiJkaWQ6ZWJzaTowMDAxMjM0NSIsInZlcmlmaWFibGVDcmVkZW50aWFsIjpbImV5SjBlWEFpT2lKS1YxUWlMQ0poYkdjaU9pSkZVekkxTmlJc0ltdHBaQ0k2SW1ScFpEcGxZbk5wT25wMlNGZFlNelU1UVRORGRtWktia05aWVVGcFFXUmxJMFl3Y2pWUGVYUmZiR0ZvZG5aNk5rMVhiRmx6TTIxaldVNUxXbWxwVVdSVlpuRjJPSFJ6YUVoT09YY2lmUS5lMzAuMFUzZzVrZjJqZDZhN1hNTjBtNXhva091UmhkSlZRZzhFR3UtclQwUVJ2bWJUbm41a0RYbi1tVWhCRWp4SVQxeFkxRmc5YWtRWlBrQmNlR3BuWXZpSFEiXX19.CfwWBrkwOYyrm93A4QEaCCKvG14G0iqr-smrUyrUyC7YBOxhSkYPZgvOy6YCsjFT59Gczd_C0K8Pbni-AH7NRQ
        presentation_submission:
          description: Descriptor for the vp_token, linked by presentation_definition. See also the Presentation Definition schema.
          type: string
          example: '{ "id": "jwt_vp with one jwt_vc", "definition_id": "Selecting JWT from credentials", "descriptor_map": [ { "id": "requested credential id", "format": "jwt_vp", "path": "$", "path_nested": { "format": "jwt_vc", "path": "$.vp.verifiableCredential[0]" } } ] }'
        scope:
          type: string
          description: OIDC scope
          example: tir_write
      required:
        - grant_type
        - vp_token
        - presentation_submission
        - scope    
    ProblemDetails:
      type: object
      properties:
        type:
          description: An absolute URI that identifies the problem type. When dereferenced, it SHOULD provide human-readable documentation for the problem type.
          type: string
          format: uri
        title:
          description: A short summary of the problem type.
          type: string
          example: Internal Server Error
        status:
          description: The HTTP status code generated by the origin server for this occurrence of the problem.
          type: number
          example: 500
        detail:
          description: A human readable explanation specific to this occurrence of the problem.
          type: string
          example: Connection timeout
        instance:
          description: An absolute URI that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
          type: string
          format: uri
    TokenResponse:
      type: object
      properties:
        access_token:
          type: string
        token_type:
          type: string
          enum: ["Bearer"]
        expires_in: 
          type: number
          description: The lifetime in seconds of the access token
          example: 3600          
        scope:
          type: string
          description: The scope of the access token
        id_token:
          type: string
          description: ID Token value associated with the authenticated session. Presents client's identity. ID Token is issued in a JWS format. See also the "ID Token" schema definition.