name: Test

on:
  push

jobs:
    unit-test: 
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Install coveralls dependencies
        run: |
          go get github.com/mattn/goveralls
          go get github.com/go-playground/validator/v10

      # Build fails due to libs missing in goroot, even when they are in the go.mod file
      - name: Workaround
        run: |
          go get github.com/gookit/goutil@v0.6.6
          go get github.com/gookit/goutil/envutil@v0.6.6

      - name: Go test
        run: |
          go test ./... -v -coverprofile=profile.cov ./...

      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov